const test=require('node:test'),assert=require('node:assert/strict'),Gemini=require('../dist/gemini.js'),KeyPool=require('../dist/key-pool.js');
test('production errors distinguish request settings and permissions without exposing keys',async()=>{
 for(const status of [400,403,429]){
  let calls=0;await assert.rejects(()=>Gemini.testConnection({key:'secret-test-key',model:'gemini-test',fetcher:async()=>{calls++;return{ok:false,status,headers:{get:()=> '90'},json:async()=>({error:{message:'response_schema rejected secret-test-key AIzaOtherHiddenKey https://example.test/?key=secret-test-key'}})};}}),e=>e.status===status&&e.retryAfterMs===90000&&e.message.includes('HTTP '+status)&&e.message.includes('response_schema')&&!e.message.includes('secret-test-key')&&!e.message.includes('AIzaOtherHiddenKey')&&!e.message.includes('example.test')&&(status!==400||e.message.includes('요청 형식')));
  assert.equal(calls,1);
 }
});
test('connection test validates synthetic product with production JSON configuration',async()=>{let usage;const result=await Gemini.testConnection({key:'test-only-key',model:'gemini-3.1-flash-lite',onUsage:x=>usage=x,fetcher:async(url,options)=>{assert(url.includes('/gemini-3.1-flash-lite:generateContent'));assert.equal(options.headers['x-goog-api-key'],'test-only-key');const body=JSON.parse(options.body);assert.deepEqual(JSON.parse(body.contents[0].parts[0].text),[{id:0,title:'주방 수납 바구니',candidates:['정리용'],brand:'',category:'주방 수납',titleWords:['주방','수납','바구니']}]);assert.equal(body.generationConfig.responseMimeType,'application/json');assert(body.generationConfig.responseSchema);assert(body.systemInstruction);return{ok:true,json:async()=>({usageMetadata:{totalTokenCount:8},candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify([{id:0,keywords:[{keyword:'정리용',status:'no_obvious_issue',reason:'용도',afterWord:1}]}])}]}}]})};}});assert.equal(result.model,'gemini-3.1-flash-lite');assert.equal(usage.totalTokenCount,8);assert(result.elapsedMs>=0);});
test('test targets exact key without changing selection or falling back, preserves cooldown',async()=>{const pool=new KeyPool();pool.add('A','project-a','fake-a');const b=pool.add('B','project-b','fake-b');let tried=[];await assert.rejects(()=>pool.test(b,async key=>{tried.push(key);throw Object.assign(Error('quota'),{status:429,retryAfterMs:120000});}));assert.deepEqual(tried,['fake-b']);assert.equal(pool.summary()[0].active,true);assert.equal(pool.summary()[1].usage.requests,1);await assert.rejects(()=>pool.test(b,()=>assert.fail('must wait')),/대기/);assert.equal(pool.busy,false);});
test('HTTP and timeout errors are clear and incomplete response is not success',async()=>{await assert.rejects(()=>Gemini.testConnection({key:'fake',model:'gemini-test',fetcher:async()=>({ok:false,status:403,headers:{get:()=>null}})}),e=>e.status===403&&e.message.includes('권한'));await assert.rejects(()=>Gemini.testConnection({key:'fake',model:'gemini-test',fetcher:async()=>{throw Object.assign(Error(),{name:'AbortError'});}}),/90초/);await assert.rejects(()=>Gemini.testConnection({key:'fake',model:'gemini-test',fetcher:async()=>({ok:true,json:async()=>({candidates:[]})})}),/완료되지/);});
