const test=require('node:test'),assert=require('node:assert/strict');
const DS=require('../dist/core.js'),Gemini=require('../dist/gemini.js'),KeyPool=require('../dist/key-pool.js');
const headers=['상품코드','상품명','키워드','배송비','반품배송비','상세정보'];
const defaults={terms:['최고','세계최초'],shipping:500,returns:500,includeZero:true,position:'end'};
const make=(data)=>DS.tableFrom(DS.stringify([headers,...data]));
test('TSV round trip preserves quoted multiline, tabs, quotes, empty cells and zero-prefixed codes',()=>{const input=[headers,['00001','주방 "바구니"','정리함','0','3000','줄1\n줄2\t값'],['00002','','','','','']];assert.deepEqual(DS.parseTSV(DS.stringify(input)+'\r\n'),input);});
test('malformed rows and duplicate headings are rejected without guessing layout',()=>{assert.throws(()=>DS.tableFrom(headers.join('\t')+'\nA\tB'),/열 수/);assert.throws(()=>DS.tableFrom('상품코드\t상품명\t상품명\t키워드\t배송비\t반품배송비\n1\ta\tb\tc\t1\t2'),/중복/);assert.throws(()=>DS.parseTSV('"unfinished'),/따옴표/);});
test('blank interior rows stay aligned; unmodified columns remain byte-for-byte strings',()=>{const t=make([['00001','최고 수납함','세계최초,정리함','3,000원','0','<div>원본\n상세</div>'],Array(6).fill(''),['00003','선반','','무료','','=TEST()']]);const rows=DS.analyze(t,defaults),out=DS.exportRows(t,rows);assert.equal(out.length,3);assert.deepEqual(out[1],Array(6).fill(''));assert.equal(out[0][0],'00001');assert.equal(out[0][5],t.rows[0][5]);assert.equal(out[2][5],'=TEST()');assert.equal(out[0][1],'수납함');assert.equal(out[0][2],'정리함');assert.equal(out[0][3],'3500');assert.equal(out[0][4],'500');assert.equal(out[2][3],'무료');assert.equal(rows[2].issues.length,2);});
test('partial matches, literal punctuation, overlaps and case variants are removed',()=>{const clean=DS.makeMatcher(['총','AB','99.9','최고','고급']);const r=clean('총알 ABab 99.9 9999 최고급');assert.equal(r.value,'알 9999');assert(r.removed.includes('총'));});
test('newly adjacent forbidden text is removed in a subsequent pass',()=>{const clean=DS.makeMatcher(['XX','AB']);assert.equal(clean('AXXB').value,'');});
test('fee parsing rejects blank, text, malformed commas, negative and formulas',()=>{for(const v of ['', '무료','3,00','-500','=3000+500'])assert(DS.fee(v,500,true).issue);assert.equal(DS.fee('0',500,false).value,'0');assert.equal(DS.fee('3,000원',500,true).value,'3500');assert.throws(()=>DS.fee('100',-1,true));});
test('repeated recalculation uses original data and does not accumulate fees',()=>{const t=make([['001','바구니','정리함','3000','6000','']]);assert.deepEqual(DS.exportRows(t,DS.analyze(t,defaults)),DS.exportRows(t,DS.analyze(t,defaults)));assert.equal(t.rows[0][3],'3000');});
test('keyword additions are staged, not exported before approval; forbidden titles cannot be approved',()=>{const t=make([['001','최고 바구니','최고,정리함','3000','6000','']]),rows=DS.analyze(t,defaults);assert.equal(rows[0].proposed,'바구니 정리함');assert.equal(DS.exportRows(t,rows)[0][1],'바구니');assert.throws(()=>DS.approve(rows[0],'최고 바구니','',defaults.terms),/금지어/);assert.throws(()=>DS.approve(rows[0],'','',defaults.terms));rows[0]=DS.approve(rows[0],rows[0].proposed,'상품 정보 확인',defaults.terms);assert.equal(DS.exportRows(t,rows)[0][1],'바구니 정리함');});
test('20,000 rows and 1,470 rules preserve all non-target cells',()=>{const terms=Array.from({length:1468},(_,i)=>'금지표현'+i).concat(['최고','세계최초']);const input=Array.from({length:20000},(_,i)=>[String(i).padStart(6,'0'),'최고 수납함','세계최초,정리함','3000','6000','원본 '+i]);const t=make(input),start=performance.now(),rows=DS.analyze(t,{...defaults,terms});for(let i=0;i<rows.length;i++){assert.equal(rows[i].output[0],input[i][0]);assert.equal(rows[i].output[5],input[i][5]);assert.equal(rows[i].output[3],'3500');assert.equal(rows[i].output[1],'수납함');}console.log('20k rows / 1470 rules:',Math.round(performance.now()-start),'ms');});
test('Gemini only accepts mapped IDs and substrings actually in data',()=>{const items=[{id:1,title:'상품',candidates:['정리용']}], value=[{id:1,keywords:[{keyword:'정리용',status:'uncertain',reason:'확인',afterWord:null}]}];assert.deepEqual(Gemini.validateResult(value,items),value);assert.throws(()=>Gemini.validateResult([{id:2,keywords:[]}],items));assert.throws(()=>Gemini.validateResult([{id:1,keywords:[]}],items));});
test('Gemini request contains no search tool, preserves 429 and handles malformed outputs',async()=>{const items=[{id:1,title:'상품',candidates:['정리용']}];let request;const result=await Gemini.check({key:'test-only-key',model:'gemini-3.1-flash-lite',items,fetcher:async(url,init)=>{request=JSON.parse(init.body);assert.equal(new URL(url).hostname,'generativelanguage.googleapis.com');return{ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify([{id:1,keywords:[{keyword:'정리용',status:'uncertain',reason:'불확실',afterWord:null}]}])}]}}]})};}});assert.equal(request.tools,undefined);assert.equal(result.length,1);await assert.rejects(()=>Gemini.check({key:'test-only-key',model:'gemini-3.1-flash-lite',items,fetcher:async()=>({ok:false,status:429,headers:{get:()=> '120'}})}),e=>e.status===429&&e.retryAfterMs===120000);});
test('key pool skips all keys in exhausted project, falls back once per distinct project',async()=>{const pool=new KeyPool();pool.add('A','project-a','key-a');pool.add('A2','project-a','key-a2');pool.add('B','project-b','key-b');const tried=[];const result=await pool.execute(async key=>{tried.push(key);if(key==='key-a')throw Object.assign(Error('limit'),{status:429});return 'ok';});assert.equal(result,'ok');assert.deepEqual(tried,['key-a','key-b']);assert.equal(pool.summary()[1].status,'quota');assert.throws(()=>pool.reset('project-a'),/대기/);assert(!JSON.stringify(pool.summary()).includes('key-a2'));});
test('pool does not fall back on auth or unknown failures; duplicate keys rejected',async()=>{const p=new KeyPool();p.add('A','project-a','abc');p.add('B','project-b','def');assert.throws(()=>p.add('C','project-c','abc'),/이미/);let calls=0;await assert.rejects(()=>p.execute(async()=>{calls++;throw Object.assign(Error('auth'),{status:403});}));assert.equal(calls,1);assert.equal(p.busy,false);});
test('XLSM reader extracts only supplied list range, never macros or local path cells', {skip:!process.env.DS_FORBIDDEN_PATH},async()=>{const fs=require('node:fs'),vm=require('node:vm'),{DOMParser}=require('@xmldom/xmldom');const window={};const context={window,Uint8Array,DataView,TextDecoder,Blob,DecompressionStream,DOMParser};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../dist/workbook.js'),'utf8'),context);const bytes=fs.readFileSync(process.env.DS_FORBIDDEN_PATH);const list=await window.readForbiddenWorkbook(new Blob([bytes]));assert.equal(list.length,1470);assert.equal(list[0],'최고');assert(list.includes('총'));assert(list.every(x=>!x.includes('C:\\')));console.log('Provided XLSM: 1470 list cells verified');});

test('candidate counts, quantity preservation and review exclusions',()=>{const t=make([['1','수납함 30cm 2개','수납함,정리용,다용도,가정용','0','0','']]);let r=DS.analyze(t,{...defaults,keywordCount:3,position:'auto'})[0];assert.deepEqual(r.candidates,['정리용','다용도','가정용']);assert.equal(r.proposed,'수납함 정리용 다용도 가정용 30cm 2개');r=DS.approve(r,r.proposed,'',[]);r=DS.applyKeywordReview(r,[{keyword:'정리용',status:'no_obvious_issue'},{keyword:'다용도',status:'suspect'},{keyword:'가정용',status:'uncertain'}],'auto');assert.equal(r.proposed,'수납함 정리용 30cm 2개');assert.equal(r.approvedName,undefined);assert.throws(()=>DS.approve(r,'수납함 다용도','',[]));assert.equal(DS.exportRows(t,[r])[0][1],'수납함 30cm 2개');assert.throws(()=>DS.analyze(t,{...defaults,keywordCount:4}));});

test('keys, selection, quota and usage survive reload; deletion erases storage',async()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};const p=new KeyPool();p.add('A','project-a','fake-a');p.add('B','project-b','fake-b');await p.execute(async key=>{if(key==='fake-a')throw Object.assign(Error('quota'),{status:429});p.recordUsage(key,{promptTokenCount:12,candidatesTokenCount:8,totalTokenCount:25});return true;});p.save(storage);const restored=new KeyPool();restored.restore(storage);assert.deepEqual(restored.summary(),p.summary());assert.equal(restored.summary()[1].usage.total,25);assert.equal(restored.summary()[0].usage.requests,1);for(const k of restored.summary())restored.remove(k.id);restored.save(storage);assert.equal(data.size,0);});
test('invalid saved state does not partially import keys and storage failures surface',()=>{const p=new KeyPool();assert.throws(()=>p.restore({getItem:()=>JSON.stringify({version:1,keys:[{label:'A',project:'project-a',key:'fake'},{}],projects:[]})}));assert.equal(p.summary().length,0);p.add('A','project-a','fake');assert.throws(()=>p.save({setItem:()=>{throw Error('denied');}}));});

test('built-in list contains 1470 unique terms and cleans titles and keywords automatically supplied as defaults',()=>{const terms=require('../dist/forbidden-terms.js');assert.equal(terms.length,1470);assert.equal(new Set(terms).size,1470);assert(terms.includes('최고'));assert(terms.includes('총'));assert(terms.every(t=>!/[A-Za-z]:\\|https?:\/\/|@/.test(t)));const table=make([['001','최고 수납함','최고,세계최초','3000','6000','원본']]);const row=DS.analyze(table,{...defaults,terms})[0];assert(!row.cleaned.includes('최고'));assert(!row.keywords.includes('세계최초'));assert.equal(row.output[5],'원본');});

test('13-column copy preserves intermediate values, blank rows and approved edits; rejects incomplete layouts',()=>{const h=DS.HEADERS;const record=h.map(n=>({'상품명':'최고 바구니','키워드':'정리함','배송비':'3000','반품배송비':'0','가격':'001200','대표 이미지':'https://example.com/image.jpg','브랜드':'원본브랜드'}[n]||''));const t=DS.tableFrom(DS.stringify([h,record,Array(h.length).fill('')]));let rows=DS.analyze(t,{...defaults,includeZero:false});rows[0]=DS.approve(rows[0],rows[0].proposed,'',defaults.terms);const block=DS.exportBlock(t,rows);assert.equal(block[0].length,13);assert.equal(block[0][0],'바구니 정리함');assert.equal(block[0][11],'3500');assert.equal(block[0][12],'0');for(const i of [1,2,3,4,6,7,8,9,10])assert.equal(block[0][i],record[h.indexOf(DS.COPY_HEADERS[i])]);assert.deepEqual(block[1],Array(13).fill(''));assert.throws(()=>DS.exportBlock(make([['1','바구니','','0','0','']]),[]),/13개 열/);});

test('AI inserts at distinct interior gaps without changing original tokens or spacing',()=>{const checks=[{keyword:'다용도',status:'no_obvious_issue',afterWord:1},{keyword:'정리용',status:'no_obvious_issue',afterWord:3}];assert.equal(DS.placeAIKeywords('주방  수납 바구니 2개',checks),'주방 다용도  수납 바구니 정리용 2개');for(const afterWord of [0,4,-1,1.5])assert.throws(()=>DS.placeAIKeywords('주방 수납 바구니 2개',[{...checks[0],afterWord}]));const t=make([['1','주방 수납 바구니 2개','다용도,정리용','0','0','']]);const row=DS.analyze(t,{...defaults,keywordCount:2,position:'ai'})[0];assert.equal(row.proposed,row.cleaned);assert.equal(row.status,'pending');const result=DS.applyKeywordReview(row,checks,'ai');assert.equal(result.proposed,'주방 다용도 수납 바구니 정리용 2개');assert.equal(DS.exportRows(t,[result])[0][1],row.cleaned);});
test('AI schema rejects endpoint positions, missing positions and inserting suspicious candidates',()=>{const items=[{id:1,title:'주방 바구니',candidates:['정리용']}];const k={keyword:'정리용',status:'no_obvious_issue',reason:'용도 수식',afterWord:1};assert.equal(Gemini.validateResult([{id:1,keywords:[k]}],items)[0].keywords[0].afterWord,1);for(const afterWord of [0,2,undefined,3,-1])assert.throws(()=>Gemini.validateResult([{id:1,keywords:[{...k,afterWord}]}],items));assert.throws(()=>Gemini.validateResult([{id:1,keywords:[{...k,status:'suspect'}]}],items));assert.equal(DS.placeAIKeywords('바구니',[{...k,afterWord:null}]),'바구니');});
